### ISSUE TITLE
Calendar always show Daily View mode when tap date At the Glance 

### ISSUE THREAD

**Issue by chanh2018** [FossifyOrg/Calendar#102]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/CONTRIBUTING.md).

### Affected app version

1.0.2

### Affected Android/Custom ROM version

Android 14 stock rom

### Affected device model

Pixel 4A 5G

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Goto Settings
2. In "View to open from the even lis widget" select Monthly and daily view
3. Goto phone home screen
4. Tap on date at At the Glance widget
5. Calendar display Daily view

### Expected behavior

It supposes to display Monthly and daily view as selected in settings

### Actual behavior

It display Daily view

### Screenshots/Screen recordings

![Screenshot_20240124-170814_Calendar](https://github.com/FossifyOrg/Calendar/assets/65605997/7d0a9dca-8897-4768-8b7f-043413c65f1d)

**Comment by Aga-C** [comment]
This option only works for the Fossify Calendar's widget, not widgets from another apps. In this case, we open the view for which the other app asks.
