### ISSUE TITLE
Custom times for notifications about events

### ISSUE THREAD

**Issue by trancephorm** [FossifyOrg/Calendar#105]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I'm a happy user of Simple Calendar Pro, but I really do miss one option. It's the default times for notifications about event. I always need to customize it because I usually want to be reminded for 2 hours before event, and only 1 hour before event is available. Would be great if we can make our own list of notification times.

### Why do you want this feature?

It could save us few actions every time we're adding events, and I do it pretty much frequently.

**Comment by min7-i** [comment]
There are already options to modify the default reminders. In settings you can either choose to use the reminder from the last created event or you can define your own default reminders. There you can also define a custom time, e.g. 2 hours:
![Screenshot_20240126-212748](https://github.com/FossifyOrg/Calendar/assets/97251923/09fe544b-adb3-4200-acf2-481d84326ddc)

**Comment by Aga-C** [comment]
@trancephorm Is the solution mentioned above enough for you?

**Comment by trancephorm** [comment]
Yes, that's it, didn't notice it. Thank you!
