### ISSUE TITLE
[Feature Request] Other sync accounts

### ISSUE THREAD

**Issue by christian179717** [FossifyOrg/Calendar#108]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

It should be possible to add own sync accounts with accounts that aren't already connected to the phone or accounts that aren't google accounts.

### Why do you want this feature?

It would be possible to sync the calendar with a privacy-friendly sync application and transfer the calendar to other devices.

**Comment by Aga-C** [comment]
The app doesn't have Internet access, so it can't do sync on its own. It always requires a third-party app (like DAVx5) to do the synchronization as phone's calendar, as it is written in app's FAQ.

**Comment by naveensingh** [comment]
I agree with @Aga-C, why not just use DAVx5 with Fossify Calendar?

**Comment by nomada-rodrigo** [comment]
Hi,
I installed Fossify calendar and Davx5 but I don't find in either apps any way of synching them together.

Davx5 app has a page to "add account", but I don't have an account on Fossify calendar to fill in the respective fields.
So how can I do this?

For some context, my goal is to synch the Fossify calendar from my phone with Thunderbird on a Linux laptop.

**Comment by Aga-C** [comment]
@nomada-rodrigo Just enable `CalDAV sync` option in Fossify Calendar Settings.

**Comment by nomada-rodrigo** [comment]
> @nomada-rodrigo Just enable `CalDAV sync` option in Fossify Calendar Settings.

I did. There is an option in the calendars list called "calendar" which allows me to synch to thunderbird. But actually that option corresponds to the mailbox calendar. So i guess that I am synching to mailbox and from mailbox to thunderbird.

What would be name of the calendar from thunderbird if it would appear in Fossify?

**Comment by chesio** [comment]
> So i guess that I am synching to mailbox and from mailbox to thunderbird.

You guess right. Thunderbird is a only a client, so you cannot connect to it directly from another client (= your phone). You have to let your calendar from Thunderbird synchronize with some server that supports [CalDAV](https://en.wikipedia.org/wiki/CalDAV) and then setup DAVx⁵ on your phone to synchronize with the same server. Finally, in order to be able to see the calendar synced via DAVx⁵ in Fossify Calendar app, you need to enable the `CalDAV sync` option.

> What would be the name of the calendar from thunderbird if it would appear in Fossify?

It's the name you have configured the first time you set up the calendar.

**Comment by shrimprugbysnowowl** [comment]
@christian179717 , I was looking for a way to sync my work calendar somehow, and I found a solution that might help you. See if the sync accounts you have allow you to publish your calendar as an *.ics link. If so, you can use ICSx5 from f-droid to sync the calendar to your android device, then check the box for the calendar in Fossify Calendar's settings under the heading CALDAV --> "Manage synced calendars".

![Screenshot_20240417-090912](https://github.com/FossifyOrg/Calendar/assets/59341190/fbd32025-b57b-4ad7-9aa8-df6ea5c63142)


I'm using K-9 Mail for work email but it does not have an integrated calendar, so I needed a workaround. Good luck!

@Aga-C where are these elusive FAQs? Not seeing them in the readme or any pinned discussion topic.

**Comment by Aga-C** [comment]
@shrimprugbysnowowl 
See the checklist in the opening post: 
> read the FAQs inside the app (Menu -> About -> FAQs)
