### ISSUE TITLE
Hide calendar selection bar at the bottom of the main screen

### ISSUE THREAD

**Issue by dktzde** [FossifyOrg/Calendar#118]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I have several CalDav calendars that I synchronise. I can show and hide them at the bottom of the main screen. I want to be able to hide this bar so that all calendars are always displayed.

### Why do you want this feature?

Unfortunately, an appointment "disappears" from time to time and I wonder why it is no longer in my diary. After a while, I realise that I have accidentally hidden the corresponding calendar.

**Comment by Aga-C** [comment]
It's already implemented. See: https://github.com/FossifyOrg/Calendar/issues/96#issuecomment-1906764943.
