### ISSUE TITLE
Show as 'Calendar' instead of 'Fossify Calendar' in lockscreen notification

### ISSUE THREAD

**Issue by jayb-g** [FossifyOrg/Calendar#131]
In the original simple calendar, all events etc notifications are shown to be from 'Calendar' in lockscreen. 

I think its better than to show 'Fossify Calendar' in notifications. Although when unlocked it shows as Calendar.

**Comment by Aga-C** [comment]
It should be just `Calendar`. If it's displayed otherwise, it means that your language's translator decided to name it this way. You can easily modify this translation on Weblate.

**Comment by jayb-g** [comment]
I'm not using any translator. Its all default

**Comment by Aga-C** [comment]
Please create a new issue filling the form properly.

**Comment by jayb-g** [comment]
@Aga-C I don't see any form/template while creating new issue

**Comment by Aga-C** [comment]
https://github.com/FossifyOrg/Calendar/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=bug_report.yml
