### ISSUE TITLE
"Go to date" does not go to the correct date in WEEKLY view

### ISSUE THREAD

**Issue by e-t-l** [FossifyOrg/Calendar#140]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.2

### Affected Android/Custom ROM version

Android 14 / GrapheneOS ROM

### Affected device model

Pixel 7

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Set calendar to weekly view
2. Tap 3-dot menu
3. Tap "Go to date"
4. Enter a date

### Expected behavior

It goes to the week containing that date

### Actual behavior

It goes to the week *one month prior* to the entered date (e.g. trying to go to Feb 4 2022 will show the week containing Jan 4 2022)

### Screenshots/Screen recordings

-

### Additional information

-

**Comment by Aga-C** [comment]
It jumps to the proper date. Try tapping a date to add an event. You'll see it's a proper date (4th February, not January). You see January on the left because this week is in both months, so you have 31st January, 1st February etc.

**Comment by e-t-l** [comment]
That's weird. It definitely was doing it with all dates, e.g. Aug 14 would take it to July 19. But I restarted the app and it's behaving properly now. I guess it was a transient bug and a restart was all it needed.
