### ISSUE TITLE
Clicking on event in widget go to editing instead of a view.

### ISSUE THREAD

**Issue by smith901** [FossifyOrg/Calendar#141]
Its rather annoying to click on an event to see details, only to be taken to editing the event.

Would be nice if it went to daily view to see the details instead of editing event then having to back out. This happens on multiple devices from Marshmallow to the current version.

**Comment by Aga-C** [comment]
Please create a new issue via https://github.com/FossifyOrg/Calendar/issues/new/choose and fill properly the form.
