### ISSUE TITLE
Crash when changing colors, only after importing settings

### ISSUE THREAD

**Issue by michaelof** [FossifyOrg/Calendar#146]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.2

### Affected Android/Custom ROM version

Android 11

### Affected device model

Nokia 7.2

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Install app
(2. optional, to verifiy correct behaviour: change default colors to light theme: everything works fine!)
3. import settings, which are previously exported from lates SimpleMobileTools Calendar app: Everything works fine!
4. change default colors to light theme

### Expected behavior

Not a big issue, if known could easyly be avoided.
But as probably a lot of users might switch this way from SimpleMobileTools Calender, maybe helpful to have this issue documented.
NO issue for new Fossify Gallery and Contacts app, export/import as described here works fine for me.

### Actual behavior

- App stops, probably because Icon color switches from new green to old orange
- when trying to start app again, launcher (KISS, from F-Droid, https://github.com/Neamar/KISS) says (translated from German:) "Ups, app could not be started"
- if this happens, deleting app data via Android settings, cache AND app data, does not solve this issue, must reinstall

### Additional information

First of all: THANKS, @naveensingh Naveen and all other contributors to keep this pretty nice set of apps alive!!!

**Comment by Aga-C** [comment]
It will be fixed in the next version: https://github.com/FossifyOrg/Commons/pull/17.
