### ISSUE TITLE
Easter missing

### ISSUE THREAD

**Issue by maverick74** [FossifyOrg/Calendar#149]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0 2

### Affected Android/Custom ROM version

Android 8.1

### Affected device model

Xiaomi redmi 5

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Install the app.
2. install Portuguese holidays
3. Go to March 2027

### Expected behavior

Easter should be marked at the 28th

### Actual behavior

There is no Easter that year!
We have good-Friday on the 26 but no Easter on the 28

**Comment by Aga-C** [comment]
See: https://github.com/FossifyOrg/Calendar/issues/84#issuecomment-1900217905.

**Comment by maverick74** [comment]
Do you think https://github.com/FossifyOrg/Calendar/discussions/11 could fix this issue or does it need to be fixed independently?
