### ISSUE TITLE
Set "Settings -> Audio stream used by reminders" to "Alarm" by default, so you hear the reminders instead of missing them

### ISSUE THREAD

**Issue by davidhedlund** [FossifyOrg/Calendar#157]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Set "Settings -> Audio stream used by reminders" has to be changed from "Notification" (text) to "Alarm" in order for the app to use the speaker.

### Why do you want this feature?

People will miss their meetings if they are sleeping and only get notified by text.

**Comment by Aga-C** [comment]
This would override the do-not-disturb setting, and we don't want to do this by default. Simple Calendar used to have this as the default, and it was changed, because it was irritating for people. Also, if someone has such a situation, that there was no sound (even when configured in Notification settings), there's always an FAQ entry about that.

**Comment by davidhedlund** [comment]
> This would override the do-not-disturb setting, and we don't want to do this by default. Simple Calendar used to have this as the default, and it was changed, because it was irritating for people. Also, if someone has such a situation, that there was no sound (even when configured in Notification settings), there's always an FAQ entry about that.

Thank you for clarifying.

**Comment by davidhedlund** [comment]
> This would override the do-not-disturb setting, and we don't want to do this by default. Simple Calendar used to have this as the default, and it was changed, because it was irritating for people. Also, if someone has such a situation, that there was no sound (even when configured in Notification settings), there's always an FAQ entry about that.

How about showing a pop-up on the first launch after installation that asks the user whether they want to enable audio alerts or activate Do Not Disturb mode?

**Comment by naveensingh** [comment]
Newer devices have system toggles to enable/disable alarms and calendar reminders when Do Not Disturb is active, so even if the preference is changed, it's not guaranteed to work. The current default is the safer default.

**Comment by davidhedlund** [comment]
> Newer devices have system toggles to enable/disable alarms and calendar reminders when Do Not Disturb is active so even if the preference is changed, it's not guaranteed to work. The current default is the safer default.

Thank you.
