### ISSUE TITLE
Start of day for week view not applied

### ISSUE THREAD

**Issue by pressing-buttons** [FossifyOrg/Calendar#198]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 8.1

### Affected device model

bq aquaris x pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open Settings
2. Scroll to "Week View
3. Change "Start day at" to e.g. 09:00

I usually use the app in German, but I switched to English to rule out a problem with the localization. The attached screenshots were taken while the app was switch to English, but the week view shows the same behaviour when switching back to German

### Expected behavior

The days in the week view start at 09:00

### Actual behavior

The days in the week view start at 00:00

### Screenshots/Screen recordings

<img alt="Settings week view" src="https://github.com/FossifyOrg/Calendar/assets/100460969/ede484a5-ba38-4781-8027-cc2bd144a2d2" width=225 />

<img alt="Week view" src="https://github.com/FossifyOrg/Calendar/assets/100460969/c5df6b1e-6bde-496b-a23b-c2f844ffea4b" width=225 />

**Comment by Aga-C** [comment]
This function is not supposed to hide these hours. They will still be displayed, but after opening the view, it should be scrolled to the given hour.
