### ISSUE TITLE
Disable dimming of past tasks when uncompleted (widget only)

### ISSUE THREAD

**Issue by ekogupta** [FossifyOrg/Calendar#203]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Provide option to disable dimming of past **tasks** when they haven't been marked as completed (**_widget only_**).

### Why do you want this feature?

Currently the _'dim past events'_ option affects both events and tasks, and applies simultaneously to the APP and widget.

Within the APP, the behavior works as desirable (the tasks are only dimmed after they have been marked as completed).

The issue is with the widget (calendar monthly), that regardless of tasks' completed state, they are always dimmed once the task time has passed.

With the current behavior - it's very easy to mistake dimmed uncompleted tasks with dimmed completed tasks, since the dimming effect is visually stronger than the strikethrough.

**Comment by Aga-C** [comment]
There shouldn't be a separate option. Tasks in widgets should look the same as in the app.

**Comment by naveensingh** [comment]
Should be fixed in the next update.
