### ISSUE TITLE
Error or bug in the Spanish version in month view

### ISSUE THREAD

**Issue by miguelmaiquez** [FossifyOrg/Calendar#205]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 11

### Affected device model

Unihertz Titan Pocket

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Set Spanish as the app language
2. Choose month view

### Expected behavior

The days of the week should appear as follows:
L M X J V S D
(corresponding to lunes -Monday-, martes -Tuesday-, miércoles -Wednesday-, sábado -Saturday- and domingo -Sunday-)

### Actual behavior

The days of the week appear as follows:
L M X J V Dom. D
(It should be "S", for sábado -Saturday-, instead of "Dom.", which seems to be short for domingo -Sunday-)

### Screenshots/Screen recordings

![calendar](https://github.com/FossifyOrg/Calendar/assets/5161774/9081c252-e54c-48e5-a7c2-4cf44cb88d51)

### Additional information

Edited: The bug also happens in Month+Daily view.

**Comment by Aga-C** [comment]
It's already fixed (https://hosted.weblate.org/translate/fossify/commons/es/?checksum=438250412d8f0998&q=saturday_letter&sort_by=-priority%2Cposition#history) and will be applied in the next app version.

**Comment by miguelmaiquez** [comment]
Hi. Do you know when that next version is going to be released? Thank you.

**Comment by naveensingh** [comment]
Soon-ish but I can't provide a solid ETA...

**Comment by miguelmaiquez** [comment]
I can see it's fixed in version 1.1.0! Thank you! :)
