### ISSUE TITLE
Inadvertently creating duplicate birthday events when importing birthdays from contacts

### ISSUE THREAD

**Issue by vivident4004** [FossifyOrg/Calendar#206]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

All

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Go to app's main menu
2. Tap on "add birthdays from contacts"

### Expected behavior

The event for the birtdays would be added only once, and the duplicates would not be added or would be merged. So, if one taps n times the import button at any n moments, there should still be only one event of each birthday for every contact. 

### Actual behavior

For every contact there are n events created (with n taps on the import button), and there is not a way, or a button, or a setting to automatically merge all birthdays for all contacts for every year in the calendar.

### Additional information

The only way to solve this is to delete the birthdays event tab completely and re-import all the birthdays, which is slightly inconvenient. It would be nice if there was a simple check to prevent this behaviour from happening.
Also, I haven't tried with anniversaries or other types of events, but I suspect the behaviour might be the same.

**Comment by Aga-C** [comment]
`Add contact birthdays` should prevent duplicates from being created. I tested it right now, and no duplicate entries have been created.

Where do you store your contacts? Do you modify contacts in any way between imports?

Also, please provide your specific device model.

**Comment by vivident4004** [comment]
I've now retested the app and indeed, no duplicates appear.
I recently moved all of my data to another phone, and on the previous phone I was using SimpleMobileTools' Calendar, and I imported all the events through a .ics backup on the new Fossify Calendar, so I guess there was a mismatch and the new app didn't properly recognize the birthday events. Now, after deleting the birthdays tab and re-importing them, no duplicates appear. I even tried adding a new birthday to a contact, and  after tapping again on `Add contact birthdays`, it gets automatically imported with no duplicates.

My bad, I should've tested it more thoroughly. Should I cancel this bug report?

The only bug now, if we can classify it as that, is after removing the birthday from a contact (in this case, the contact I modified for the test) it is not automatically removed from the calendar, even after tapping again on `Add contact birthdays`.

I have the stock contacts app on a Pixel 8.

**Comment by Aga-C** [comment]
> after removing the birthday from a contact (in this case, the contact I modified for the test) it is not automatically removed from the calendar, even after tapping again on Add contact birthdays

There's already a similar issue: https://github.com/FossifyOrg/Calendar/issues/194, so we are aware that this synchronization needs a refinement.

**Comment by Satlinker** [comment]
Similar problem with teracube and iode-os.
I sync a birthday calendar over CalDav. The birthdays appear twice in fossify. On PC they appear right, once in my thunderbird calendar.
If I delete the birthdays, they reappear twice. This should be right, because the CalDav calendar is write-protected.
I cannot find any option to remove birthdays from contacts.
