### ISSUE TITLE
Update holidays Nederland

### ISSUE THREAD

**Issue by PanderMusubi** [FossifyOrg/Calendar#215]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 11 / LineageOS 18.1

### Affected device model

OnePlus 8T

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to menu
2. Choose add holidays
3. Choose Nederland (Netherlands)

### Expected behavior

Up to date Dutch holidays 

### Actual behavior

Out of date Dutch holidays. It contains Queensway 30 April 2024, while the last was in 2013. Also some new additions are missing.

The app source file

https://github.com/FossifyOrg/Calendar/blob/master/app/src/main/assets/netherlands.ics

should be a copy of the upstream version

https://github.com/PanderMusubi/dutch-holidays/blob/master/NederlandseFeestdagen.ics

Please add in the build process an automated check if this file needs to be updated with upstream.

### Additional information

Please give this issue a high priority as outdated holiday info can have costly consequences.

**Comment by PanderMusubi** [comment]
Nice!

What do you use as upstream? For the Netherlands, please don't use the one offered by Thunderbird. They use the same upstream eventually, but can also lag behind as they don't check for updates automatically.

Additionally, Thunderbird has changed the way they generate holiday ICS files and caused also for missing holidays for the Netherlands. This is an ongoing issue, so sidestep them for NL for the holiday calendar.

**Comment by tswistak** [comment]
I will answer, since I implemented it. We don't use Thunderbird's database, but https://github.com/commenthol/date-holidays. Here's explanation why: https://github.com/FossifyOrg/Calendar/pull/152#discussion_r1513902357

**Comment by PanderMusubi** [comment]
Thank you for the explanation. That is another source and I will contact them to make some improvements and additions.
