### ISSUE TITLE
Only use primary language on dual language systems 

### ISSUE THREAD

**Issue by seniordevel** [FossifyOrg/Calendar#219]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 11

### Affected device model

Gigaset GS4

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1.In Android settings configure primary and secondary language.
2. Go to calender view on dual language android
3. Look at the bottom

### Expected behavior

Text should be in english only

### Actual behavior

You see:

Regular event (correct, primary language is english)
...and on the right;
"Regulaerer Termin" in german

### Screenshots/Screen recordings

<img alt="Screenshot_20240428-173246" src="https://github.com/FossifyOrg/Calendar/assets/129897917/b549739d-8a7f-424e-93a9-031feeebc912" width=184 />

**Comment by Aga-C** [comment]
1. Have you installed the app while OS primary language was English, or German?
2. I see you have events in "Regulaerer Termin". Were they created in the app, or imported from an ICS file?

**Comment by seniordevel** [comment]
> 1. Have you installed the app while OS primary language was English, or German?
> 
Primary language was english.

>     2. I see you have events in "Regulaerer Termin". Were they created in the app, or imported from an ICS file?

Imported from ICS file. I migrated from Simple Tools to you(Fossify)

Thus possibly it is NOT your fault, but a bug in Simple Tools export function. (good questioning, thank you)

**Comment by seniordevel** [comment]
> Just to be sure - you had "Regulaerer Termin" in Simple Calendar?

No, defiantly no. Simple Tools Calender always appeared in english, any text.
Therfore I wonder why - after import of ICS- some text appears in german.

By the way, thete is another case, I forgot to mention here, please see following screenshot:

![Screenshot_20240428-203004](https://github.com/FossifyOrg/Calendar/assets/129897917/13a8766a-e288-46a0-be62-0f7110a28f4e)

On "new task" there also appears "Regulaerer Termin"

**Comment by Aga-C** [comment]
I have some follow-up questions, because I tried to reproduce it with two languages on a device and always had a proper name.
1. In the ICS file under `CATEGORIES`, do you have "Regular event", or German name?
2. During importing, have you checked `Ignore event types in the file`?

About the problem with new events, probably in Settings you have set `Default event type` as `Last used one`, that's why you have this German one as default.

If you'd like to remove that German event type, go in Settings to `Manage event types`, remove the unwanted type, and during deleting you will be prompted what to do with events. Check there `Move affected events into the default event type`. It should move everything to "Regular event".

**Comment by seniordevel** [comment]
> I have some follow-up questions, because I tried to reproduce it with two languages on a device and always had a proper name.
> 
>     1. In the ICS file under `CATEGORIES`, do you have "Regular event", or German name?
> 
Unfortunately I yet deleted the ICS file, and in the TotalCommander filemanager app there is no trash to restore. I would have attached ICS, but no way. 

>     2. During importing, have you checked `Ignore event types in the file`?
> 
I think no, but I am not sure/cannot remember, sorry


> 
> About the problem with new events, probably in Settings you have set `Default event type` as `Last used one`, that's why you have this German one as default.
> 
This applies:

![Screenshot_20240428-211510](https://github.com/FossifyOrg/Calendar/assets/129897917/9d281be0-6ca2-45f9-9887-12bac6banyway!



> If you'd like to remove that German event type, go in Settings to `Manage event types`, remove the unwanted type, and during deleting you will be prompted what to do with events. Check there `Move affected events into the default event type`. It should move everything to "Regular event".

Thank you, I did so.

![Screenshot_20240428-211839](https://github.com/FossifyOrg/Calendar/assets/129897917/634ff14a-bff4-4cc9-b356-25385f3ee852)



Thus -for me the problem is solved- 
But for other users possibly not, since only few users find the way to Github.

Your decision to leave this issue open or to close it.

Thank you anyway
