### ISSUE TITLE
CalDav event (Davx5) not showing want start time = end time

### ISSUE THREAD

**Issue by titibandit** [FossifyOrg/Calendar#223]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 11 / LineageOS 18.1

### Affected device model

Samsung Galaxy S7

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Create an event with the same start and end times, on a caldav synced calendar.
(The event will appear in the calendar)
2. Sync the caldav calendars
(The event will disappear and never come back)

### Expected behavior

Same as above, except that the event get synchronized back to the device.

### Actual behavior

After getting through a synchronization with Davx5, the event will never show up again.

### Screenshots/Screen recordings

https://github.com/FossifyOrg/Calendar/assets/2920044/e6cf0d64-5abd-4caf-a5b9-5828d6272c64

### Additional information

While using other devices and synchronization adapters (for example, vdirsyncer for computers) I can see that the events are still there. But not when synced with Davx5.
I've signaled this on the Davx5 repository (https://github.com/bitfireAT/davx5-ose/discussions/753#discussioncomment-9260468) and the assumption is that the Fossify calendar, when the event is created with start time = end time, there is no DTEND property to the underlying event created, and Fossify calendar handles that well. And when getting through Davx5, the DTEND property is created (see the discussion of Davx5's repo) on the event, and Fossify Calendar has trouble displaying that.
This is just speculation, but this sounds plausible.

**Comment by Aga-C** [comment]
I tested the same path but with Google Calendar, and everything works properly. For me, it seems like a bug in DAVx5, not in Fossify Calendar.

Have you checked if other calendar apps on your phone display this event?

**Comment by titibandit** [comment]
You're right, exactly the same behavior is to be observed with the etar calendar app for example...
I'll update the opened conversation on Davx5's repo.

**Comment by titibandit** [comment]
I'm gonna write this message in both the trackers of Fossify Calendar and Davx5, as both sides think the other is at fault (and both sides might be right, or both wrong I don't know :o) )

I don't know which side is more "wrong" and thus where a solution should be deployed, but this behavior is clearly not expected and not ideal. I haven't taken the time to debug this more thoroughly, but the behavior is very predictable and reproducible.
A very obvious workaround is to not make events that last 0 seconds, but some other people are bound to fall in that trap, especially since Fossify cal's default duration for events is actually 0 hours if I'm not mistaken.
