### ISSUE TITLE
New event color does not match event color defined in settings

### ISSUE THREAD

**Issue by seniordevel** [FossifyOrg/Calendar#225]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 11

### Affected device model

Gigaset GS4

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Tap on + .... choose Event
2. create new event
3. Go to calender view, see color of new event

### Expected behavior

The colors on new event tab, as well as the color of the new event should match the color defined in settings (manage event types)

### Actual behavior

The color of new created events is completely different.

### Screenshots/Screen recordings

<img alt="Screenshot_20240505-194120" src="https://github.com/FossifyOrg/Calendar/assets/129897917/32f56118-1011-41bc-b442-dfaee31af1c0" width=184 />
<img alt="Screenshot_20240505-194105" src="https://github.com/FossifyOrg/Calendar/assets/129897917/a7094f07-a71b-402f-a069-786207eb4fb1" width=184 />
<img alt="Screenshot_20240505-194015" src="https://github.com/FossifyOrg/Calendar/assets/129897917/6d031b48-c76b-499a-825b-4694c3c235c5" width=184 />

**Comment by Aga-C** [comment]
We don't have separate categories for events and tasks. Your new event is created under `Regular task` category, that's why it has its color. And the color of your event, which is in `Regular task` category, is the same color as `Regular task` in the settings.
