### ISSUE TITLE
Wrong new event color

### ISSUE THREAD

**Issue by seniordevel** [FossifyOrg/Calendar#226]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

11

### Affected device model

GS4

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Referring to #225

Do not close an issue just by guessing what might have gone wrong.

No, definitely no, I choosed EVENT, not task, I repeated this several times.

And yes, new event has same color as task, but should have blue color.

Also see screenshots I posted at #225 
The screenshots are in reverse order

### Expected behavior

.....

### Actual behavior

.....

### Screenshots/Screen recordings

.....

**Comment by Aga-C** [comment]
Instead of opening a new issue, you could just comment in an old one. Also, what you've described is not the same as I wrote. You've created an event with a category `Regular task`, that's why you have that color.

**Comment by seniordevel** [comment]
>You've created an event with a category Regular task

No I tapped event, at the bottom, not task above

![Screenshot_20240505-202341](https://github.com/FossifyOrg/Calendar/assets/129897917/5faacbdf-4b55-4ebd-9729-6af9954466f3)

And category events are defined in blue as you see here

![Screenshot_20240505-202223](https://github.com/FossifyOrg/Calendar/assets/129897917/d74ee81d-f846-49da-80a7-4fcf8083ca69)

**Comment by Aga-C** [comment]
That's what I mean. You're creating an event with `Regular task` category.

![signal-2024-05-05-20-40-15-631.png](https://github.com/FossifyOrg/Calendar/assets/85929121/21789e73-4966-4e73-8260-998e3d0c94d8)

**Comment by seniordevel** [comment]
> That's what I mean. You're creating an event with `Regular task` category.

Thank you!

But should not new event default to 'Regular event' not to 'Regular Task'?

As there are two different buttons, task and event, the defaults in new * should be set accordingly, otherwisse choosing type after pressing + button is kind of redundant.

Ibask, before considering to open a new enhancement issue

**Comment by Aga-C** [comment]
> But should not new event default to 'Regular event' not to 'Regular Task'?

When you run the app for the first time, there's only `Regular event` category. Either you created `Regular task` on your own, or you imported it from another source. That's why we didn't even consider this case. And as I said in the original issue, we don't have separate categories for events and tasks.

> I ask, before considering to open a new enhancement issue

If you like, you can create, but consider the fact, that there's no `Regular task` category in a clean app installation. However, you may ask for a separate manual setting of a default category for events and tasks. But I can't promise you that we will take it into development.

**Comment by seniordevel** [comment]
Thanks again, and yes I imported events and settings from original 'Simple Tools', now unfortunately commercial.

I understand that the two defaults, Event and Task are gone. Still you can create new event types, that's useful, e.g. to add reminders for special days.

>>However, you may ask for a separate manual >>setting of a default category for events and >>tasks. 

Wouldn't it be better, to ask for removal for event type buttons, which appear after pressing the + button. I mentioned this in my previous post:

>>choosing type after pressing + button is kind of redundant.

I mean it is redundant, because you need to define the type anyway later on the new event screen.  Exactly this was my problem, you marked it in red on a screenshot I sent.

The option to choose event types with seperate buttons suggests, that the event type is defined already. For me this is irritating somehow.

For developers, removing those buttons and the related piece of code is much more less effort.
