### ISSUE TITLE
Remove redundant event type buttons

### ISSUE THREAD

**Issue by seniordevel** [FossifyOrg/Calendar#227]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 11

### Affected device model

Gigaset GS4

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Define at least two event typrs in settings
2. Go to calender view
3. Press + button

### Expected behavior

The app should not ask to choose the event type after pressing the + button.

This behavior is kind of redundant, since the app always defaults to the default event type defined in settings.

It makes no important difference which event type you choose with those buttons.

In many cases you need to define event type again on the bottom.of the following 'New Event' screen, just above event color.

The option to choose event types with seperate buttons suggests, that the event type is defined already. For me this is irritating somehow.

Please also see discussion with Aga-C, after issue #226 was closed.

### Actual behavior

The app asks to choose event type after pressing + button.

**Comment by Aga-C** [comment]
> The app should not ask to choose the event type after pressing the + button.
> This behavior is kind of redundant, since the app always defaults to the default event type defined in settings.

These are two separate things. An event is not the same as a task, and choosing an event type doesn't determine whether something's an event or a task. You are confusing these ideas. Events are regular calendar entries that have specific duration, can take place in a specific location and have other attendees. Tasks are more like reminders, TODO items.

Event type is just for categorizing events and tasks. It's the same as having different calendars in Google, Outlook or anything like this. Just because you have defined an event type `Regular task` (which isn't a standard type in this app) it doesn't mean it's the same as creating events or tasks. You can create other event types like `Appointments`, `Birthdays`, `Holidays`, and create either events or tasks under them. 

Since these are completely separate things in the app, I close this issue. If it confuses you, just remove the `Regular task` event type. App will still behave the same.

**Comment by seniordevel** [comment]
Still confusing, I removed the task event type as you suggested.

The two event type buttons are still available.
So, as those are different categories such as different calendars, I would expect that this difference is made visible in clear way, such as different default colors. But in calender there seems to be no difference, except the category name, shown only in detail view.

>>We don't have separate categories for events and tasks

Well, sad as events and tasks are comparable to different calenders as you wrote.

So you might allow to request diffetent default colors for events and tasks?

**Comment by chesio** [comment]
> Still confusing, I removed the task event type as you suggested.

Think of a calendar as a normal paper calendar where you can put notes about both **events** and **tasks** - both entities are related to time, but there is a difference:
* Event has a timespan and location.
* Task can have a start date or due date. Task can have progress (0%, 50%, ...).

Think of **event type** as **name for you calendar**. You can have more calendars: personal, work... You can name the calendar "Regular tasks" or "Regular events", but still have both events and tasks stored in the calendar (hence the confusion).

Now to the UI:
1. The two "+" buttons allow you to select what you want create: event or task.
2. On new event/task screen, you then select the calendar where you want the event/task to be stored. This however does not change entity type: an event stays an event even if you select store it in calendar named "Regular tasks" (and vice versa for task and a calendar named "Regular events").

Btw. I see where your confusion comes from, the use of term "event types" for calendar names is perhaps not the best UI/UX.

**Comment by chesio** [comment]
> The two "+" buttons allow you to select what you want create: event or task.

One more note: if you only use the app for events (like I do), you can turn off the "+" button for tasks in the settings.

**Comment by chesio** [comment]
> We should probably replace the concept of 'event types' with 'local calendars'.

Perhaps a good start would be to collect all occurences of this term in the app. Then decide (or vote? 😄 ) on the best replacement that works in all contexts.

**Comment by seniordevel** [comment]
Thank you for all the answers. Very helpful.

>Btw. I see where your confusion comes from, the use of term "event types" for calendar names is perhaps not the best UI/UX.

>We should probably replace the concept of 'event types' with 'local calendars'.

Yes, I think this could be an improvement.

But the other point of confusion has not been mentioned here:

I never recognized any visual diffrence between events and tasks in calender view. It needed a hint with screenshot where Agniezka ecplicitely pointet out that there is a small task icon in calender view!

Please be aware that many aged persons (I am still under 60 years) have problems reading small text. Especially if not focused, e.g. trying to capture a whole month in calender view. Even the best spectacles won't compensate.

Thus I hope task and events will have different default colors in the future.

**Comment by seniordevel** [comment]
By the way, I agree and I consider it as useful to have two categories 
- for tasks like appointments and dates ... and
- for events like holidays

There is a different color option for weekends available already, but not for events

**Comment by naveensingh** [comment]
> decide (or vote? 😄 ) on the best replacement

I think I see what you did there ;)

It will be announced (at least using a feature request) because changes like this always alienate at least some users.

Come to think of it, there should also be an **option** to save/insert these private calendars into the Android database so that they can be managed using other calendar apps.

**Comment by seniordevel** [comment]
> One more note: if you only use the app for events (like I do), you can turn off the "+" button for tasks in the settings.

Well, but additionally I activated the built-in holidays feature. Now everything works fine for me.

Now I have seperate default colors for holidays and tasks. 

Perfect solution for me!
Thanks for all your help in general, and this note/hint in special.

**Comment by Aga-C** [comment]
That's because the first holiday has been created as a single occurrence event because it has a moving a date. You're just prompted then about deleting that one particular event.

The second event is repeating because that holiday is always on the same date. That's why the app is asking what specifically you want to remove.

**Comment by Aga-C** [comment]
@seniordevel If you have more questions about how the app works, please use [Discussions](https://github.com/FossifyOrg/Calendar/discussions) for it.
