### ISSUE TITLE
Moving task events to default event type fails

### ISSUE THREAD

**Issue by seniordevel** [FossifyOrg/Calendar#229]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 11

### Affected device model

Gigaset GS4

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Migrate from Simple tools to this app
2. Export/Import settings, events and tasks
3. Delete type tasks in event type management(settings)
4. You will be asked to either delete all tasks or to move them to default event type => choose MOVE !

### Expected behavior

Former task type events are still visible as default events in calender

### Actual behavior

Any former tasks are completely lost, nothing moved, but deleted

**Comment by Aga-C** [comment]
It affects all tasks, not only imported.

**Comment by naveensingh** [comment]
It'll be fixed in the next update.
