### ISSUE TITLE
Task sync with davx5

### ISSUE THREAD

**Issue by noonehere998877** [FossifyOrg/Calendar#231]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

As Calendar events sync with davx calendar I want tasks should also be synced.Currently tasks are only kept offline.

### Why do you want this feature?

This will help me to sync my tasks to nextcloud instance I use and to my Linux machine.

### Additional information

Tasks are also stored as Caldav data. Probably implemening that file as another option to save task will do the job.
(English is not my first language)

**Comment by noonehere998877** [comment]
It is duplicate issue.
Apology for unconvince.

**Comment by Aga-C** [comment]
https://github.com/FossifyOrg/Calendar/issues/36
