### ISSUE TITLE
Allow Client Certificate Login with Nextcloud

### ISSUE THREAD

**Issue by seifer44** [FossifyOrg/Calendar#242]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I'm running a NextCloud server that requires a client certificate to log in, in addition to NextCloud's normal authentication.

* When I attempt to run a **Provider-specific login** for NextCloud against a URL of https://example.com, I'm granted with an error _Couldn't obtain login URL_.

### Why do you want this feature?

**Advanced Login** already supports client certificates. I'm guessing this wouldn't be too much work to add in :smile: 

### Additional information

When I run an _Advanced Login_ of https://example.com/remote.php/dav/calendars/USERNAME/CALENDARNAME, type in my Nextcloud username and password, and select a client certificate installed on the device, this is also not successful.

### Nginx Proxy Configuration Example

The following is configured on my internet-facing NGINX. This hands off to Apache hosting Nextcloud. It's important to note that my mobile Android clients are able to log into Nextcloud with client certs on the Nextcloud mobile app.

```
server {
  listen 443 ssl http2;
  ssl_certificate /etc/example.com_fullchain.pem;
  ssl_certificate_key /etc/example.com_privkey.pem;
  ssl_client_certificate /etc/ssl/certs/private-ca.crt;
  ssl_verify_client on;

  ssl_dhparam /etc/ssl/certs/dhparam-2048.pem;

  location / {
    proxy_pass https://example.com:443;
    proxy_redirect off;

    proxy_set_header Upgrade           $http_upgrade;
    proxy_set_header Connection        "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Port  $server_port;
    proxy_hide_header x-powered-by;
  }
}
```

**Comment by Aga-C** [comment]
Fossify Calendar doesn't have an Internet permission, so for CalDAV synchronization we rely completely on third-party apps. The app only accesses calendars that are already in the system, and uses Android mechanisms to force synchronization. Therefore, it's not on our side to implement it.
