### ISSUE TITLE
Protection against "screenshot" and "recent apps" from other prying apps

### ISSUE THREAD

**Issue by serrq** [FossifyOrg/Calendar#243]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Adding an ON/OFF switch to enable/disable privacy mode.

### Why do you want this feature?

I close the gate before the sheeps go away.

### Additional information

Privacy enhancement.

**Comment by Aga-C** [comment]
Please raise issues regarding all apps in https://github.com/FossifyOrg/General-Discussion/issues.
