### ISSUE TITLE
Event types and colours are not included in Export Settings

### ISSUE THREAD

**Issue by AndyM48** [FossifyOrg/Calendar#249]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Include Event type Names and Colours created in Calendar Settings exported file. 

### Why do you want this feature?

Personalised event types and colours have to be recreated if starting a FC on a new device. I would have expected these to be included in the exported settings.

**Comment by Aga-C** [comment]
Event types and colors are exported along with the events itself. Isn't it enough?

**Comment by AndyM48** [comment]
No, because for future entries of events the event types would have to be redefined.

**Comment by Aga-C** [comment]
Importing event types with events isn't temporary. Once they are created while importing events, they stay and can be used for any new event.

**Comment by AndyM48** [comment]
Thank you. I don't think that worked when I tested it, I will try again shortly.

**Comment by naveensingh** [comment]
> I would have expected these to be included in the exported settings.

Perhaps it should be mentioned in the export settings dialog that events and event-types/calendars are not part of this export.
