### ISSUE TITLE
In shared Google calendar, events created by the other person are not shown

### ISSUE THREAD

**Issue by Domingato** [FossifyOrg/Calendar#258]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 10

### Affected device model

Galaxy S9 SM-G960W

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

Open the app
Select the calendars (google calendars in this case) to sync

### Expected behavior

See all the events in all selected calendars

### Actual behavior

See all events in all calendars, except:
for a shared Google calendar with someone else, I don't see the events that are created there by the other person.
I do see the events created by me in this calendar.
I also see the events created by the other person in this calendar in the official Google Agenda app.

I tried to sync this particular calendar using DAVx5.
In this case, a second calendar appears in the Fossify app, with the same name of course. But no events at all are shown for this additional calendar.

**Comment by Domingato** [comment]
Update: I went to the Google Agenda app, unselected the problematic calendar, and selected it again.
It seems to have magically solved the problem.
The problem was there for days and I tried so many things, including restarting the phone of course. But nothing did the job like what I just did apparently.

**Comment by Aga-C** [comment]
> It seems to have magically solved the problem.

Do you also get new events now?

**Comment by Domingato** [comment]
I do. We may close the ticket but I'd suggest to first do some test or code
verification first, or at least add the workaround in the docs/FAQ.

Le jeu. 20 juin 2024 01 h 59, Agnieszka C ***@***.***> a
écrit :
