### ISSUE TITLE
edit color of a single caldav event

### ISSUE THREAD

**Issue by krzemyczek** [FossifyOrg/Calendar#264]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

it would be nice to have an option to edit a single caldav event color like  in "Store locally only" 

### Why do you want this feature?

i use calendar to track garbage collection and i like having plastics, paper etc. in different color so i just by looking know what type of trash will be collected

### Additional information

it should be easy fix as it is locally only (i thing)

**Comment by Aga-C** [comment]
You can already edit the color of a single event, even if it's synchronized by CalDAV. It's at the bottom while editing an event. If you don't see this, it may be a problem with an app that does the synchronization, that it doesn't allow setting colors.
