### ISSUE TITLE
Import of ICS does not respect setting "Use last event's reminders..." for new events

### ISSUE THREAD

**Issue by michaelof** [FossifyOrg/Calendar#269]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 10

### Affected device model

Nokia 7.2 (which has a heavy battery drain issue also with FossifyCalendar :))

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open ICS file (which contains many events)
2. Select desired calender for import
3. import

### Expected behavior

For each imported event from ICS file, as working fine for manually created events, the last event's reminders should be used as template

### Actual behavior

All imported events have no reminders

### Additional information

Background: As our domestic refuse collection org is simply not able to provide somehow reliable notifications generated by their "waste service app", for years and many versions now (also Android), they good luck are providing now the possibility to download a street address specific yearly calender, downloadable as ICS. Unfortunately, this ICS or the events contained don't have any reminders set. Which should be, of course, a pity. They are imported fine by FossifyCalendar, but they are many, e.g. in my case 91 for 2024, paper waste, organic waste, plastics, "normal" waste,... Germany :)
A pain in the neck to change them one by one, and also no mass update possible in FossifyCalendar, AFAIK.
So: Would be cool to have this the same way than for manually entered events.

**Comment by Aga-C** [comment]
Your actual behavior is the expected behavior for import, since we respect what's in ICS files. What you described is a new feature in the app, not a bug. 

We already have a similar feature request for setting reminders in badly created calendars. You can write your use case there: https://github.com/FossifyOrg/Calendar/issues/236.
