### ISSUE TITLE
Setting a default event length doesn't change the default event length

### ISSUE THREAD

**Issue by SnuggleCovenant** [FossifyOrg/Calendar#273]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14 GrapheneOS

### Affected device model

Pixel 7

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Set default event duration 35 minutes
2. Double tap calendar to make a new event (not using [+] button)

### Expected behavior

New event popup should be 35 minutes long

### Actual behavior

New event is 1 hour long

**Comment by Aga-C** [comment]
It's an expected behavior. In a weekly view, you're tapping on an hour long time span, that's why it always defaults to 1 hour.
