### ISSUE TITLE
Doesn't Sync Without Google Calendar

### ISSUE THREAD

**Issue by Godly-Avenger** [FossifyOrg/Calendar#274]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

q.0.4

### Affected Android/Custom ROM version

Android 11 / Stock Android

### Affected device model

Nokia X100

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Uninstall Google Calendar (I was trying to Degoogle my phone).
2. Attempt to sync calendars.

### Expected behavior

I expect it to be able to sync calendars without Google Calendar.

### Actual behavior

When I try to sync calendars, it says it's synced but it doesn't update. In the account's section in Android Settings the Calendars option in the sync section for all accounts is gone.

**Comment by Aga-C** [comment]
> q.0.4

There's no such version of Fossify Calendar.
