### ISSUE TITLE
"Calander Today's Date" widget not displaying properly

### ISSUE THREAD

**Issue by ArrowSwift509** [FossifyOrg/Calendar#275]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Pixel 8

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

Note: I am using Nova Launcher
1. Touch and hold on the home screen in order to bring up the widget select panel
2. Select the "Calander Today's Date" from the menu and put it on the home screen
3. Once the colors have been selected, you will see that the widget is only half the size that it should be.

### Expected behavior

The widget should take up a full 2x1 or 2x2 section of the home screen, or at least be centered.

### Actual behavior

Takes up half of the 2x1 section or a quarter of the 2x2 section of the home screen, and is justified towards the top instead of center.

### Screenshots/Screen recordings

<img alt="Screenshot_20240716-130507" src="https://github.com/user-attachments/assets/d7d4eb6c-e278-4bbc-9dee-f75c48042d6b" width=180 />
<img alt="Screenshot_20240716-130503" src="https://github.com/user-attachments/assets/e432d3b3-5c44-4b5e-b9f3-5d6de73ede2c" width=180 />

### Additional information

As stated previously, I am using Nova Launcher.

**Comment by naveensingh** [comment]
Should be fixed in the next update.
