### ISSUE TITLE
Sorting in simple event list

### ISSUE THREAD

**Issue by antodc** [FossifyOrg/Calendar#289]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When choosing the simple event list, the oldest event is shown first. I thing the newest should appear instead.

### Why do you want this feature?

I am usually intetested in newer events, not the older ones.

**Comment by Aga-C** [comment]
1. Do you mean the event list widget or the event list view in the app?
2. By oldest and newest event, you mean events that are happening at the same time?

**Comment by antodc** [comment]
Sorry for not being clear.

1) I meant the view in the app. No idea about the widget.

2) I have recorded my running performances in the calendar since 2019. When I use that view I see firstly the 5-years old records and I have to scroll the full list to see the most recent ones. Maybe my personal usage, but I think it would be more natural to see first the events closer to the current date.

**Comment by Aga-C** [comment]
It sounds like a bug because by default it should display events from the current day at the start.

I have some more questions:
1. Is this calendar synced via the Internet, or is it local?
2. What have you set in Settings → Event lists → Display events from the past?
3. Do you see on the search bar the icon with calendar? If not, please scroll view up or down and tap it. Does it scroll to the current date?
4. After performing the action from point 3, please try to change view to another one (e.g. daily or monthly) and come back to the event list. Does it still open view on 2019, not today?

**Comment by antodc** [comment]
1) Sync with internet 

2) 10,000 days

3) I did not notice that icon before. Yes, it scrolls to current date.

4) I did as you said, and now it shows the current date. Even after closing-reopening the app, now it shows the current date.

So, the ‘problem’ seems to be solved.

If I may add, I would prefer to see the current date on top of the list, and scroll down to go to past events. But my opinion.

**Comment by antodc** [comment]
Some additional information. What I said before was true because I add a future event. If I delete that event (ie I only have past events) the calendar icon does not bring me to the most recent past event and if I change view it show again 2019 events first. So, in order to work properly, it seems that the calendar has to have future events in it.

**Comment by Aga-C** [comment]
Thanks for clarifying! Solving this issue: https://github.com/FossifyOrg/Calendar/issues/209 will also fix your bug, since the current date will always be present in the list.
