### ISSUE TITLE
Choose Multiple Days of the Week for Custom Task Repitition

### ISSUE THREAD

**Issue by eggsnpie** [FossifyOrg/Calendar#290]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Provide a days-of-the-week selection screen for if the user needs to have a task repeat on specific week days instead of just on a numerical basis.

### Why do you want this feature?

There are some tasks I currently have associated with things I only need to do on specific days of the week. These tasks are not associated with the numerical day they need to be done. They are associated with certain weekdays that I need to be reminded to do these tasks.

### Additional information

Here I have attached a comparable feature that is included in the Fossify Clock app for alarms.

![alarm-wd-selection_screenshot](https://github.com/user-attachments/assets/0dc619fa-4eb4-414b-a1be-a2dfa5f460b1)

**Comment by Aga-C** [comment]
It's already implemented. Choose weekly repetition, and in`Repeat on` you can select specific week days.
