### ISSUE TITLE
Calendar  event reminder pop up bubble

### ISSUE THREAD

**Issue by AdmFubar** [FossifyOrg/Calendar#297]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

android 11

### Affected device model

u319aa

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

adding an event to the calendar, when completed the pop up bubble stating the time till the event is off by two days. 

### Expected behavior

it should report the correct number of days.

### Actual behavior

see above

**Comment by Aga-C** [comment]
Can you be more specific in steps, expected and actual behavior? Also, please provide a screenshot if possible. I can't reproduce this bug.
