### ISSUE TITLE
Mark Task as Completed in notification pop up

### ISSUE THREAD

**Issue by BrilliantTrees** [FossifyOrg/Calendar#300]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Pixel 8

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Adding a TASK to calendar works as expected as do any time specific reminders associated with the task and if you choose to mark task as Complete from within the calendar itself by opening the specific task and scrolling to  the bottom and selecting the "Mark Completed" button then all works as expected and the task is struck through with a line and no further reminders are triggered

However if you get a NOTIFICATION pop up on the top of your phone screen (when task time reminder is triggered) and view this notification on phone home screen there is an option to "Mark Complete" to allow the notification to be dismissed. This does not appear to be working and the task remains open and marked as incomplete if you subsequently open the calendar in Monthly and Daily View.

### Expected behavior

To be able to mark the task as complete (and strike the entry through with a line) directly from the notification pop up option that says "Mark Complete"

### Actual behavior

As above

### Screenshots/Screen recordings

.

### Additional information

.

**Comment by Aga-C** [comment]
1. Does it happen for all tasks? Or only for recurring ones?
2. When you open the task details, does it say that it's completed?

**Comment by BrilliantTrees** [comment]
I only have recurring tasks but set up a one off as a test after receiving your response and the Mark Completed option from the Pop Up notification has worked perfectly both dismissing the Android reminder and when I open the Calendar I can see the task marked as complete and crossed through...........so all good.

On for instance a monthly recurring task I'm able to open the calendar and mark the August 16th task as complete and this crosses it through and leaves the 16/09 and subsequent repeat tasks live and uncrossed and I will get reminders for those.

But if I try to "Mark as Complete" the 16/08 task through the Android notification then it dismisses the notification but leaves the 16/08 task as Open in calendar view. 

Ideally on a recurring task it would mark just the current reminder (that's triggered the notification) as complete while leaving subsequent occurrences as live to trigger subsequent reminders

Thanks

**Comment by Aga-C** [comment]
Thanks for explanation. It's a known issue: https://github.com/FossifyOrg/Calendar/issues/156.
