### ISSUE TITLE
Disable Notifications in shared Calendar

### ISSUE THREAD

**Issue by tomdereub** [FossifyOrg/Calendar#302]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Choose to disable reminders and notifications for some shared calendars.

### Why do you want this feature?

I'm using several calendars synced with davx5 to android with different persons. I would like to see their events, but not receive notification from their events, that are just annoying me. But I need to receive reminders from my calendars.

### Additional information

There is already an open issue on davx5 : https://github.com/bitfireAT/davx5-ose/issues/466, but I don't know if it will be implemented one day, and don't know if it's better to integrate this feature on davx5 side or on calendar app side ?
Is it possible to implement it on fossify calendar ?

**Comment by Aga-C** [comment]
We already have a request for setting reminders for the whole calendar, so when it is implemented, you can also use it the other way around: https://github.com/FossifyOrg/Calendar/issues/236.

**Comment by tomdereub** [comment]
No, it's not the same feature. In my case, I don't want to remove reminders of a calendar, I just don't want to see notifications from this calendar. I try to be clearer : 
- people A and B are sharing each others calendars
- people A needs to receive notification from reminders of her own calendar. She want's to see B's events, but without receiving notification from his calendar
- peaple B needs to receive notification from reminders of his own calendar. He wan'ts to see A's events too, but without receiving notification from her calendar.

So the aim is not to modify reminders, but just be able to disable notification from a calendar. In thunderbird, it looks like this : 
![image](https://github.com/user-attachments/assets/9ac54988-d130-4cce-8235-9c0d8c2bfca9)
There is a check box to see or not notifications of events.

**Comment by tomdereub** [comment]
That's right, thank you very much ! I had not seen that disabling notifications here was per calendar.

**Comment by fapdash** [comment]
@Aga-C Is this still supposed to work? When I go to Settings → Customize notifications I see the following:

<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/5b230cfd-2336-461a-a444-ef4c397b2d9b" width=197 />

> If a notification from a given calendar type has once fired, it should be available to modify there.

I definitely had a notification fire from one of the calendars before.

I'm syncing the calendars via CalDav, if that's relevant.

**Comment by naveensingh** [comment]
@fapdash, please enable "Manage notification categories for each app" in System settings ➜ Notifications ➜ Advanced settings. More info is [here](https://www.androidpolice.com/samsung-disables-notification-channels-on-all-one-ui-61-devices).

**Comment by fapdash** [comment]
@naveensingh Thank you so much, now it's working!
