### ISSUE TITLE
Incorrect Timezone in Code

### ISSUE THREAD

**Issue by bartoshevich** [FossifyOrg/Calendar#303]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Pixel 8

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1) Navigate to app/src/main/kotlin/org/fossify/calendar/helpers/MyTimeZones.kt

2) Note that the expected GMT offset for "Asia/Almaty" should be GMT+5 (since 2024), not GMT+6 

### Expected behavior

The correct association should be "GMT+5" for "Asia/Almaty"

### Actual behavior

The code incorrectly associates "Asia/Almaty" with "GMT+6", which results in an incorrect time calculation.

### Screenshots/Screen recordings

![изображение](https://github.com/user-attachments/assets/20fb3ad3-14af-49f3-8944-863175762720)

**Comment by igoose1** [comment]
Hi, I second it! I spent two hours trying to find why my computer's events delay for an hour compared to my phone's event (I use CalDAV), and I'm finally happy to find a reason! I'm indeed in Almaty currently, my computer's tzdata is correct and it seems an issue is in manually updated [app/src/main/kotlin/org/fossify/calendar/helpers/MyTimeZones.kt](https://github.com/FossifyOrg/Calendar/pull/307/files#diff-519829409a3027bcf24e2b5cf4357d93e3629202bf0cbab772125f3afbdd5eb7).

This PR seems okay for now: https://github.com/FossifyOrg/Calendar/pull/307/files

**A better PR** would update all timezones: https://www.joda.org/joda-time/timezones.html

**The best PR** would replace self-hosted timezone database with `java.util.TimeZone`: https://developer.android.com/reference/java/util/TimeZone

I've never programmed for Android, although I can help to investigate how to do this right.

**Comment by naveensingh** [comment]
Should be fixed in the next update.
