### ISSUE TITLE
Bangladeshi holidays missing

### ISSUE THREAD

**Issue by kvhjdffv** [FossifyOrg/Calendar#304]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Hello. I have been using the Fossify Calendar app and I love it. It's a very nice app to use. But, there aren't any options to have Bangladeshi holidays. That's an issue because I am from Bangladesh. Please add this feature as soon as possible 

### Why do you want this feature?

I want this feature because I live in Bangladesh and I need to check if today/tomorrow/a certain day's a holiday.

**Comment by StyingDev** [comment]
> I created #347, can you help to review it? The dates are based on [publicholidays.com.bd](https://publicholidays.com.bd/2025-dates/) with national mourning day [removed](https://en.wikipedia.org/wiki/Public_holidays_in_Bangladesh#Former_holidays).

@curbengh 
I have checked the national holidays they look fine. Although the dates may not be accurate for the religious holidays for Islam. As some are calculated with for example by the phases of the moons.
I see no issues besides that.
