### ISSUE TITLE
Calendar shows only the 3 first reminders

### ISSUE THREAD

**Issue by guy-teube** [FossifyOrg/Calendar#308]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14 / LineageOS 21

### Affected device model

Google Pixel 4A

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Create a event outside Fossify Calendar application: Thunderbird+Lightning, default calendar of the system, [Etar Calendar](https://github.com/Etar-Group/Etar-Calendar/)...
2. Create 4 or more reminders on this event
3. Save the event
4. Open Fossify Calendar and synchronize the celendar

### Expected behavior

If 4 or more reminders have been created, they are all displayed in Fossify Calendar

### Actual behavior

Only the 3 first reminders are displayed in Fossify Calendar. The fourth (and nexts) are not displayed.

### Screenshots/Screen recordings

Example with Etar Calendar (4 reminders created):
![Screenshot_20240826-110642_Agenda](https://github.com/user-attachments/assets/4c3f877d-8625-41e5-94b0-31c3fbfe8581)

Only 3 reminders are shown in Fossify Calendar:
![Screenshot_20240826-110705_Agenda](https://github.com/user-attachments/assets/c3d521d1-ea05-4e16-80e4-9ff47f2fe85b)

**Comment by Aga-C** [comment]
Currently, we don't support more than 3 reminders. There's already a feature request for this: https://github.com/FossifyOrg/Calendar/issues/139.
