### ISSUE TITLE
Prevent new entries from revealing hidden event types

### ISSUE THREAD

**Issue by nvllz** [FossifyOrg/Calendar#32]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
It appears to be a feature that when adding a new entry with a hidden event type, it automatically gets revealed. I would appreciate having an option to prevent these entries from being displayed on the calendar screen when creating a new event.
To reproduce:
1. Hide any event type from display using the filter icon
2. Create a new entry/task with this hidden event type
3. Notice all linked entries associated with this specific event type get revealed

**Describe the solution you'd like**
I'd prefer a setting switch or default behavior that avoids revealing hidden event types in the calendar grid when creating a new entry.

**Describe alternatives you've considered**
Enable users to independently control the visibility of event types directly within the entry creation/edit screen. This ensures that the event type remains hidden in the filter menu until manually unhidden and doesn't get automatically unhidden with a new entry.

**Comment by Aga-C** [comment]
It was done on purpose: https://github.com/SimpleMobileTools/Simple-Calendar/pull/2133.

**Comment by naveensingh** [comment]
@nvllz I don't exactly remember why but I think it was an internal SMT task to address some related issue.
