### ISSUE TITLE
New calendar events disappear after syncing with Davx5 and PurelyMail.com 

### ISSUE THREAD

**Issue by NuLL3rr0r** [FossifyOrg/Calendar#338]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

15

### Affected device model

Pixel 8 Pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

I've used SimpleCalendar and Davx5 with an SOGo instance installed by iRedMail for many years and it has been working flawlessly. Recently however I've migrated my mail server to PurelyMail.com. I've [created a CalDav calendar](https://purelymail.com/manage/createCaldavCalendar) and exported my old events to an .ics file. Then once I setup SimpleCalendar and Davx5 to use the PurelyMail account and imported the .ics file on SimpleCalendar it worked.

I've just figured FossifyOrg/Calendar is a fork of SimpleCalendar while looking at their issues. So, I installed FossifyOrg/Calendar and it's the same issue.

However, after that, any new event I create will disappear. I've checked every setting on both apps there's nothing insane that does not make sense. It should be working. Maybe it's a PurelyMail issue, but I'm not sure honestly and don't know how to diagnose or address this. Also found that someone on https://github.com/SimpleMobileTools/Simple-Calendar/issues/427 has a similar issue.

### Expected behavior

The calendar events should sync with the server and should not delete the new calendar event.

### Actual behavior

It delets the newly created events after sync.

**Comment by titibandit** [comment]
As far as I found out a few months ago, the problem lies on purelymail's side. See https://github.com/ScottPeterJohnson/purelymail-issues/issues/222

**Comment by balintbarna** [comment]
I have the exact same issue. Did anyone report it on DAVx5?

**Comment by bronson** [comment]
> Anyways what's the meaning of 0 a minute event?

Anything where you don't know or care about the duration? Start of Race, Summer Solstice, Low Tide, etc.

**Comment by balintbarna** [comment]
My bad, I just found the setting to set default event duration to whatever I want!

**Comment by balintbarna** [comment]
By the way, this is now fixed in purely mail and works as expected
