### ISSUE TITLE
Caldev events' color reset after caledar synchronization

### ISSUE THREAD

**Issue by sebastiano123-c** [FossifyOrg/Calendar#339]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

GrapheneOS 2024092900

### Affected device model

Pixel7a

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

0. Have two mail accounts, each one with itsown different calendar. (I do not know if the bug shows up also with only one account);
1. Use DAVx5 as caldav provider and associate the two emails with a caldav;
2. Go to calendar app and enable 'CalDAV sync' in 'Menu -> Settings' (I also enabled 'Enable pull-to-refresh from the top');
3. Go to 'Menu -> Settings -> Manage event types';
4. Note that the two caldav events associated to the two emails have the same color (a sort of light blue/cyan);
5. Change the colors of the two events associated to the two email caldav;
6. Exit the 'Menu' view and notice that the modification is correctly applied to the calendar;
7. Now pull-to-refresh from top;
8. After the refresh, the bottom bar shows the events with the colors I chose, but looking at the calendar the first caldav's events become cyan again and the second caldav's events assume the color I chose for the first caldav.
9. After a second refresh, both caldav events turn back to original cyan color. Now this applies also to the bottom bar, both caldav turn back to cyan color.

### Expected behavior

After choosing two different colors for two different caldav events in 'Menu -> Settings -> Manage event types' these colors remains untouched after synchronization.

### Actual behavior

After choosing two different colors for two different caldav events in 'Menu -> Settings -> Manage event types' these colors turn back to their original cyan color after two synchronizations. This happens also in the bottom bar showing the two caldavs. 
The bug seems not to touch the regular events.

**Comment by sunkup** [comment]
DAVx5 dev here. This is expected behaviour when "Account Settings" -> "Manage calendar colors" is turned on. 

@sebastiano123-c  Try disabling it inside the Account Settings in DAVx5.

It does not matter whether you use one or two "mail" accounts.

**Comment by Aga-C** [comment]
If it's DAVx5 expected behavior, there's nothing to do on our side.
