### ISSUE TITLE
Add ability to update birthdays in Android contacts

### ISSUE THREAD

**Issue by dot-clear** [FossifyOrg/Calendar#35]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [ ]  I have read the FAQ and my problem isn't listed. (I don't find it)
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
I can't update Birthdays/anniversaries in the contact database.

**Describe the solution you'd like**
I would like any updated or new birthday will be added to the Android contacts.

**Describe alternatives you've considered**
I don't have alternatives for now.

**Additional context**
Birthdays can be imported in the app. But when new dates need to be added, they are not updated on the contacts database.

**Comment by Aga-C** [comment]
I think it would make things too complicated because we would need to bind an event to the contact. It's easier to update dates in contacts itself and then use a synchronization in Calendar.

@naveensingh What do you think?

> I have read the FAQ and my problem isn't listed. (I don't find it)

The FAQ is inside each app (three dots -> About -> FAQ).

**Comment by naveensingh** [comment]
This doesn't seem like something a Calendar app should do. Use the Contacts app for this. 

I think we shouldn't allow editing these (constructed) birthday events in the first place or at least show a notice when users try to edit them.
