### ISSUE TITLE
Notifications shouldn't be sensitive

### ISSUE THREAD

**Issue by schklom** [FossifyOrg/Calendar#361]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 15 / GrapheneOS

### Affected device model

Pixel 6a

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Make a calendar event with reminder in 1min
Pair phone with smartwatch (e.g. Garmin)
Notification of event is "sensitive" and the content is hidden from the watch
(Not talking about lock screen)

### Expected behavior

A month ago, this was not happening. Smartwatch notifications had event content

### Actual behavior

Smartwatch notifies me that an event is there, but all content is deemed "sensitive and hidden"

### Additional information

https://support.google.com/googlepixelwatch/thread/284558238/pixel-watch-2-hiding-sensitive-notifications?hl=en

mentions that this is up to the app developer, so here I am with this issue :P

**Comment by Aga-C** [comment]
When it was working a month ago, did you have Android 14? Because the app hasn't been updated since March.

**Comment by schklom** [comment]
Yes, i updated to 15 a few days ago.

**Comment by naveensingh** [comment]
Fossify Calendar doesn't override notification visibility, see https://github.com/SimpleMobileTools/Simple-Calendar/pull/429

You may try the following:

- Go to system settings => Security & privacy => More privacy settings => Notifications on lock screen => Choose "Show all notification content".
    
If that doesn't work, perhaps you added Fossify Calendar to [private space](https://developer.android.com/about/versions/15/features#private-space)? If not, this may just be a new Android/GrapheneOS bug/feature.

**Comment by schklom** [comment]
It seems it isn't individual apps' faults, but an Android 15 thing that still is not solved.
https://www.reddit.com/r/android_beta/comments/1dzx583/garmin_notification_for_otps/ answers worked.

SOLUTION 1:
Settings > Notifications > Disable "Enhanced notifications"

SOLUTION 2:
Uninstall the Garmin Connect App
Forget the device on the phone in the Bluetooth settings
Restart the phone
Restart the Garmin/Android watch
Install the Garmin Connect App
Pair the phone with the watch and complete the set-up

SOLUTION 3:
`adb shell appops set com.garmin.connectiq RECEIVE_SENSITIVE_NOTIFICATIONS allow` and replace the app name with the one that transfers notifications to other device.

Note that 1 and 3 work for KDE Connect as well
