### ISSUE TITLE
Swedish holidays not functioning correctly

### ISSUE THREAD

**Issue by holmgrendev** [FossifyOrg/Calendar#365]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung Galaxy A53

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

1. Go to "Add holidays"
2. Select "Sweden"
3. Go to Jan 1

### Expected behavior

All holidays should have the correct date

### Actual behavior

Some of the holidays have incorrect dates:

1. Alla helgons dag
2. Allhelgonaafton
3. Midsommarafton
4. Midsommardagen

They all have the date 01/01 every year.

**Comment by Aga-C** [comment]
It should be fixed in 1.1.0.
