### ISSUE TITLE
Can't delete pre-existing event type

### ISSUE THREAD

**Issue by T0mstone** [FossifyOrg/Calendar#373]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Calendar/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

Android 14 / LineageOS 21

### Affected device model

Fairphone 3+

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to the 'Settings > Manage Event types' and add a new event type
2. Go to 'Settings > New Events > Default event type' and change it to the newly created one
3. Go back to 'Settings > Manage Event types' , click on '…' for the previously existing event type (I think the default name was "Recurring Event") and click "Delete"

### Expected behavior

The selected event type is deleted.

### Actual behavior

A popup says "Default event type cannot be deleted"

### Additional information

The device is rooted (but I doubt that is relevant to this issue).

**Comment by Aga-C** [comment]
See: https://github.com/FossifyOrg/Calendar/issues/150#issuecomment-1946167183.

**Comment by T0mstone** [comment]
Hm, I feel like this is an unnecessary technical limitation. You should at least be able to change which of the existing event types is the fallback (even if it has to be a separate thing from the "default event type").

I won't ask that of you, but would you mind if I try implementing it myself and open a PR if I get something done?

**Comment by Aga-C** [comment]
@T0mstone https://github.com/FossifyOrg/Calendar/issues/150#issuecomment-2475576450
