### ISSUE TITLE
Multiple Dots for MonthDayView

### ISSUE THREAD

**Issue by themangosteen** [FossifyOrg/Calendar#38]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
The MonthDayView is one of the main reasons I switched to Tibi's "SimpleMobileTools" Calendar from DigiCal a while ago. However there was an important function missing. Instead of showing just one dot for any number of events on a day, it is very helpful to have one dot for each event. The dots have the colors of their event type. That then allows a quick mental overview over how many events of certain type are on that day. For example "Ah on that day I have uni, and later work, and then meet a friend". 

**Describe the solution you'd like**
I wrote an example implementation and will provide a pull request that hopefully will be helpful.

**Additional context**
- Screenshot of draft example implementation I made
![Pasted image 1](https://github.com/FossifyOrg/Calendar/assets/6226784/b3b8bb8e-cb08-4cc6-84d4-63ee0c626ff8)
![image](https://github.com/FossifyOrg/Calendar/assets/6226784/1de7a93a-bdf7-4ec3-8c7d-fe3887bad35c)
- Screenshot of how the proprietary DigiCal solved the MonthDay view: 
https://digibites.nl/digical/views#mView
- The old issue in SimpleCalendar 
https://github.com/SimpleMobileTools/Simple-Calendar/issues/1701

**Comment by naveensingh** [comment]
Gotta be honest, I don't like the idea of multiple dots very much. It seems a bit excessive/crowded but I'll be reviewing the PR soon. To people reading this, please comment why you like/dislike this feature.

**Comment by themangosteen** [comment]
Thank you. I think it is important to consider the ramifications of having just one dot while having multiple calenders. If there is just one dot, the information given by it is that there is an event on that day, but nothing else. Imagine I have a calendar for paid work that is green and one for personal events that is blue, and one for uni that is yellow. If I see just a blue dot, I just know that there is one event, but in worst case might be mislead to believe there are no paid work and no uni events on that day. With multiple colored dots for each event, there is a quick overview that can be connected to the mental map of the day, to quickly review: "Ah on that day I have uni, then paid work, then I meet a friend". There is a reason why the designers of DigiCal use this feature. The alternative when having just a single dot, then the dot should have a neutral color, to not misguide.

**Comment by themangosteen** [comment]
Here are also some references of people wishing for or expressing support for this feature in other calendar projects:

- https://wordpress.org/support/topic/need-multiple-dots-on-one-day/
- https://github.com/SundeepK/CompactCalendarView/issues/52
- https://www.reddit.com/r/androidapps/comments/16n7dba/what_you_consider_to_be_the_best_calendar_app/
- https://discussions.apple.com/thread/2221828
- https://discussions.apple.com/thread/250923882

**Comment by naveensingh** [comment]
@themangosteen thanks for the links, my comment was more about how it looks (the UI) but I see its usefulness now and I'm convinced but for now, let's only display 3 dots and a single row. We'll iterate once there is some more feedback from the users.

### 8 dots vs 3 dots:

<img src="https://github.com/FossifyOrg/Calendar/assets/36371707/20f09061-f9e5-449f-8352-b074c88a7a6b" width=264 /> <img src="https://github.com/FossifyOrg/Calendar/assets/36371707/91abcc38-c4ad-45d3-8b96-90aab136d188" width=264 />

I left some comments on the PR: https://github.com/FossifyOrg/Calendar/pull/39#pullrequestreview-1927762304

**Comment by naveensingh** [comment]
> Could we use 4 dots instead of 3? :)

I thought you would say that and I tried 4 dots too but 3 seems like a good start to me. We'll 'make it configurable' **or** 'increase the number of dots' **or** 'make the month view adaptive/resizable/collapsable' based on feedback from the users.

**Comment by naveensingh** [comment]
> I am not a professional software engineer

you did good anyway :)

**Comment by themangosteen** [comment]
> > Could we use 4 dots instead of 3? :)
> 
> I thought you would say that and I tried 4 dots too but 3 seems like a good start to me. We'll 'make it configurable' **or** 'increase the number of dots' **or** 'make the month view adaptive/resizable/collapsable' based on feedback from the users.

That sounds great!! Thanks again, and thanks for the compliment, had not done any software development stuff in a longer time haha 😊

**Comment by Aga-C** [comment]
Fixed in https://github.com/FossifyOrg/Calendar/pull/39.
