### ISSUE TITLE
No "go to date" in event list view 

### ISSUE THREAD

**Issue by madduck** [FossifyOrg/Calendar#400]
When I have my events displayed in list view, there seems to be no way to jump to a specific date. The Go To menu item only exists in the other views. It would be useful to be able to jump to a date in event list view too.

**Comment by madduck** [comment]
What template is missing? When I create this issue using the app, I get no template. The README says nothing about it. This isn't exactly a friendly experience but sure…

**Comment by naveensingh** [comment]
Are you using the official Github app? It should redirect you to a browser if you select "Bug report" on [this page](https://github.com/FossifyOrg/Calendar/issues/new/choose).

**Comment by madduck** [comment]
No, I am not running proprietary software on my phone. I am using FlatHub, like I've been using for years. I don't think anyone ever closed an issue as "not planned" within 20 minutes without a single word of explanation. Of course I looked over the existing issues. I am quite annoyed to be honest, but I'll now go and fill in this template…
