### ISSUE TITLE
Calendar backup encryption

### ISSUE THREAD

**Issue by Zafrkant** [FossifyOrg/Calendar#404]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

First I want to thank developers for great contribution to the community.
I would like to kindly propose feature request for calendar backup encryption.

Thank you in advance.

### Why do you want this feature?

Upload backup to cloud storage.

**Comment by Aga-C** [comment]
There are backups in multiple Fossify apps. Please raise such issues in https://github.com/FossifyOrg/General-Discussion/issues.
