### ISSUE TITLE
FR: Quiet reminders

### ISSUE THREAD

**Issue by Anke** [FossifyOrg/Calendar#44]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
I'm often frustrated when the reminder alarm beeps forever while I'm on the phone, in a meeting or whatever. I only need loud notifications for a few realy important events, but for most events a quiet reminder in the status bar and on the home screen would be quite sufficient.

**Describe the solution you'd like**
I would like to have an option to activate or deactivate sound notifications for each reminder.

**Describe alternatives you've considered**
I don't know, maybe a respective option could be added at the bottom to the reminder settings window, like "with/without sound"? (If it's possible at all to control sound notifications per event/task).

**Additional context**
BTW: I'm using the latest SMT Simple Calendar version, since I cannot find FossifyCalendar on F-Droid yet.

**Comment by Aga-C** [comment]
I think it would add too much complexity to the events. What do you think @naveensingh?

**Comment by Anke** [comment]
Thank you very much for your feedback, which just gave me the idea to check the options provided in Android settings (settings -> all apps -> simple calendar -> notifications). And I see that there can choose between "default" and **"silent" per category**. 

I think that would do for my needs; I could create an "important" category with default notifications. (If you don't want to get into this feature for other users, you can close this issue.)

Now, I'll just have to find out, why only 3 of my about 10 categories are currently listed there.

**Comment by chesio** [comment]
> Now, I'll just have to find out, why only 3 of my about 10 categories are currently listed there.

Blind guess based on categories that I have listed on this screen on my phone: I see only event categories from events that already triggered system notification before.

**Comment by Anke** [comment]
Sounds plausible, thanks.

**Comment by naveensingh** [comment]
Ok, let's close this for now then. If this is requested again, we'll think about it.

**Comment by drzraf** [comment]
I have another use-case for this : a shared caldav intended as a "program / overview" rather than individual events. I'd like to silence this whole particular calendar.

**Comment by naveensingh** [comment]
>  I'd like to silence this whole particular calendar.

The solution [described above](https://github.com/FossifyOrg/Calendar/issues/44#issuecomment-1880964303) is still the best way to handle this:

Fossify Calendar ➜ Settings ➜ Customize notifications ➜ Choose your calendar (notification category) ➜ Select "Silent"

> Blind guess based on categories that I have listed on this screen on my phone: I see only event categories from events that already triggered system notification before.

This is still true, but future versions will create notification categories right when a calendar is added to allow customization without waiting for an event to fire.
