### ISSUE TITLE
Not all notifications are shown

### ISSUE THREAD

**Issue by gokceozan** [FossifyOrg/Calendar#53]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
Some event notifications do not appear when they should have. This is extremely random -- for example, an event notification from the same calendar/notification category appears, but another event notification from the same calendar/notification category does not. Even though the same calendar/notification category appears on the settings and is active.

Over the last 24 hours, I only have 11 notifications from the app, where on any day I should have **at least** 13 (see Exhibit C).

I have 12 synched calendars (see Exhibit A) but only 6 of them appear in the notification categories (see Exhibit D).

**To Reproduce**
N/A - related to notifications. No steps involved.

**Expected behavior**
Notifications appear when there are notifications attached to the events.

**Screenshots**

#### Exhibit A Synced Calendars
![synced calendars](https://github.com/FossifyOrg/Calendar/assets/1352027/84abba95-cc47-4d18-9735-cc8aec3c59e3)

#### Exhibit B Event
![event](https://github.com/FossifyOrg/Calendar/assets/1352027/32853bd1-3534-424a-b641-a93d684e965a)

#### Exhibit C Notifications in Last 24 Hours
![notifications-24-hours](https://github.com/FossifyOrg/Calendar/assets/1352027/abbaf25b-6e12-499a-bfa1-7aad7f5c3279)

#### Exhibit D Notification Categories
![notification-categories](https://github.com/FossifyOrg/Calendar/assets/1352027/5f6c67e2-f7bd-4e7b-bd2d-5f95bcedc367)

**Device info (please complete the following information):**
 - Model: Samsung Galaxy S21+ 5G / SM-G996B/DS
 - OS: Android 14 / Samsung One UI 6.0
 - App version 1.0.2

**Additional context**
> [!NOTE]
> I migrated from Simple Calendar (by exporting my settings from that app and importing to Fossify Calendar app). On the previous app, no notification issues were present.

My events are served through CalDav syncronization on a personal NextCloud server - synced through [DAVx⁵](https://play.google.com/store/apps/details?id=at.bitfire.davdroid).

App source: Directly from GitHub (through [Obtainium](https://github.com/ImranR98/Obtainium)).

**Comment by Aga-C** [comment]
If it was working on Simple Calendar, maybe you had some system settings set regarding battery optimization or working in the background? If yes, you have to set it manually for Fossify Calendar and see if problem still exists.

**Comment by naveensingh** [comment]
I agree, this could be due to battery optimization.

**Comment by gokceozan** [comment]
And you both would be right. I thought I checked everything, but apparently, I was wrong.

Thanks!
