### ISSUE TITLE
Several seconds until calendars are displayed 

### ISSUE THREAD

**Issue by topcaser** [FossifyOrg/Calendar#6]
Hi, if I open the calendar app, the monthly view is shown instantly but my calendars need quite some seconds until they show up. This is very annoying performance problem. I am on Pixel 8 pro running graphenos. Calendars are synced via caldav. SimpleMobileTools Version never had this issue. I am using this version

Version 6.19.0

com.simplemobiletools.calendar.pro.debug
versionCode 221

targetSdk 31
minSdk 21

Installed: 03.12.2023; 22:13

**Comment by Aga-C** [comment]
This app wasn't officially released and 6.19.0 is an old version. You've probably downloaded one of the test builds.

**Comment by topcaser** [comment]
Don't understand how I can get the latest build. I am using obtainium and it installs this version. In fdroid I don't find this version at all

**Comment by trizen** [comment]
The latest version on [F-droid](https://f-droid.org/en/packages/com.simplemobiletools.calendar.pro/) is 6.23.1.

You can download it from here: https://f-droid.org/repo/com.simplemobiletools.calendar.pro_240.apk

**Comment by Aga-C** [comment]
@topcaser This fork wasn't officially released, so please wait until release (about 1-2 weeks) with adding repo to Obtainium. Until then, please use the original Simple Calendar version from F-Droid that @trizen has linked.

@naveensingh Maybe it's worth removing old test releases, so it won't mislead people?

**Comment by naveensingh** [comment]
@Aga-C yeah, I will delete them now
