### ISSUE TITLE
Colour customisation in "Manage event types" keep reverting to default

### ISSUE THREAD

**Issue by floatingatoms** [FossifyOrg/Calendar#62]
**Checklist**
 - [X] I can reproduce the bug with the latest version. 
 - [X] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [X]  I have read the FAQ and my problem isn't listed.
 - [X]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [X]  This issue contains only one bug.
 - [X]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
Choosing a custom colour for a synchronised calendar under "Manage event types" does not stick. The colour reverts back to the default colour after a few minutes (or closing and reopening app)

**To Reproduce**
1. Go to "Settings"
2. Click on "Manage event types"
3. Click the colour of an event type to choose a different colour, press "OK" to save the new colour
4. Back in the "Manage event types" menu you see the chosen colour, press back to go to calendar overview and confirm colour choice there too
5. Exit app (swipe up and "close" app)
6. Reopen app after a while to see that the chosen colour has reverted to the previous colour

**Expected behavior**
For the chosen colour to stick as a choice

**Device info (please complete the following information):**
 - Model: Pixel 7a
 - OS: GrapheneOS (Android 14)
 - App version: 1.0.2

**Comment by Aga-C** [comment]
Which calendar service are you using for CalDAV? Because I tested it with Gmail and it works fine.

**Comment by floatingatoms** [comment]
> Which calendar service are you using for CalDAV? Because I tested it with Gmail and it works fine.

Damn. There is a DAVx5 option "Manage calendar colours" which if enabled resets calendar colours on every synchronisation. Wonder if that's a new setting or not or whether the default value changed... Thanks!
