### ISSUE TITLE
Touch is broken for Pixel 8 Pro

### ISSUE THREAD

**Issue by popogomo** [FossifyOrg/Calendar#7]
As described here: https://github.com/SimpleMobileTools/Simple-Calendar/issues/2277

Multiple other users reported the same issue.

**Comment by Aga-C** [comment]
Please treat this as a completely new issue and adjust your bug report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/bug_report.md).

We don't know if old issues won't disappear, so it's better to not link to them.

**Comment by m4teh** [comment]
Yep same. Needs fixing for sure.

**Comment by Doc-4** [comment]
Can report that I also have this bug with the exact same environment.

**Comment by m4teh** [comment]
Forced to move to Etar, which is unfortunate.
Even manual entry with specific dates places it in a completely random other date. Completely unusable on Pixel 8/pro
