### ISSUE TITLE
Timezone is ignored when importing an .ics file

### ISSUE THREAD

**Issue by maximbaz** [FossifyOrg/Calendar#71]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.

> I'm actually not sure what FAQ this refers to... [this one](https://github.com/FossifyOrg/General-Discussion#faq)? Could you please add a link? :slightly_smiling_face: 

 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

> The link on "contributions guidelines" points to the same FAQ page... ? 

**Describe the bug**
Importing an .ics ignores the timezone, resulting in an event saved with a wrong time.

This is likely a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1795, I apologize if I should not have created an issue in this repo, I couldn't find any policy about this. The bug is valid and important for anyone who works across time zones, so I hope there's value in tracking it here.

**To Reproduce**

1. Take this `invite.ics` created by Google Calendar. The event is scheduled for 11:45 EET / 10:45 CET.

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/Athens
X-LIC-LOCATION:Europe/Athens
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
TZNAME:EEST
DTSTART:19700329T030000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
TZNAME:EET
DTSTART:19701025T040000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Athens:20240116T114500
DTEND;TZID=Europe/Athens:20240116T124500
DTSTAMP:20240115T103216Z
ORGANIZER;CN=John Smith:mailto:john@smith.com
UID:888888@google.com
CREATED:20240115T084412Z
DESCRIPTION:-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~
 :~:~:~:~:~:~:~:~::~:~::-\nExample\n-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:
 ~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
LAST-MODIFIED:20240115T103215Z
LOCATION:Online
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Meeting
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

2. Tap on the file, and use Fossify Calendar to open it.

**Expected behavior**
The event is saved at 11:45 EET / 10:45 CET, regardless of your local time zone.

**Actual behavior**
The event is saved at 11:45 of your phone's timezone - so if you phone is set to use CET, it will save it at 11:45 CET.

**Workaround**

1. On step 2 of repro steps, pick Etar instead of Fossify Calendar. 
2. After Etar parses the event, it will again offer to pick a calendar app - **now** pick Fossify Calendar.
3. Thanks to Etar's correct parsing, Fossify Calendar will offer to save event at 10:45 CET as expected.

**Screenshots**
N/A

**Device info (please complete the following information):**
 - Model: Pixel 7a
 - OS: Android 14
 - App version 1.0.2 from IzzyOnDroid

**Comment by Aga-C** [comment]
> I have read the FAQ and my problem isn't listed.

This FAQ is inside each app (three dots -> About -> FAQ).

> I apologize if I should not have created an issue in this repo, I couldn't find any policy about this.

You don't have to apologize, Fossify is a continuation of SMT :)

**Comment by juantxorena** [comment]
This didn't fix fully the timezone problem. When importing this ics file:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
BEGIN:VEVENT
DTSTART:20240628T093000
DTEND:20240628T100000
SUMMARY:Ihr Termin mit *****
LOCATION: ***** , 
END:VEVENT
END:VCALENDAR
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
```

when in the same timezone as described, it will create an event at 11:30 instead of 9:30. If I import it with google calendar it works correctly. I think it's because it's reading the start time as UTC, so it applies the timezone offset, when it's a "floating" date-time, as per the [specs](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.5). The previous version 1.0.2 works, probably because it ignores the timezone information. Importing this file in Google Calendar works as expected (event at 9:30, not at 11:30).
