### ISSUE TITLE
add export/import functionality for event types

### ISSUE THREAD

**Issue by Renner0E** [FossifyOrg/Calendar#85]
I have a lot of event types that rotate regularly.
So migrating from SMT is very tedious. Because there is AFAIK no obvious way to export them.
You'd have to create all the events manually again.

Is there an easy way I might have missed migrating from SMT to FossifyOrg? Copying some file with no root access. ADB?

Maybe it would be appropriate for an option in the Migrating Tab in Settings. This doesn't solve my specific issue but at least it would not be a problem anymore for those in the future who get a new phone or something like that.

Thanks for continuing all the work of SMT.

**Comment by Aga-C** [comment]
In Migrating section in Settings, there are already `Export events to an .ics file` and `Import events from an .ics file` options for that.
