### ISSUE TITLE
Design Enhancements for Dynamic Theme

### ISSUE THREAD

**Issue by SpaceFrrog** [FossifyOrg/Calendar#86]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
It is not related to a problem, but I would suggest a change to the design! The current colors of the dynamic themes do not correspond to those in the Material Design Guidelines. 

**Describe the solution you'd like**
They are much lighter than described there. For example, the background color of the FAB is A1-400 in dark mode, but according to the Material Guidelines it should be A1-700. I would be happy if this could be adjusted for all components of the app.

**Additional context**
[Add any other context or screenshots about the feature request here.
](https://m3.material.io/components)
https://m3.material.io/theme-builder#/dynamic
![Calendar_Colors](https://github.com/FossifyOrg/Calendar/assets/105725665/0856808b-419e-4812-903d-bc5acb1f5075)
![Color_Chips](https://github.com/FossifyOrg/Calendar/assets/105725665/c45d016f-a1af-4049-b3df-b1d107dca3b8)

**Comment by Aga-C** [comment]
Please add your remarks to the general issue about dynamic theme: https://github.com/FossifyOrg/Calendar/issues/41.
