### ISSUE TITLE
Ability to hide events that are a week in the future on list view widget.

### ISSUE THREAD

**Issue by a73s** [FossifyOrg/Calendar#90]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
I don't need to see multiple weeks of my reoccurring events (or any event) in advance, especially not on the widget. 

**Describe the solution you'd like**
It would be perfect if I could set a time interval, maybe a week or a month where any events older than that will not be shown on the widget list view.

**Describe alternatives you've considered**
Idk

**Additional context**
I thought simple calendar did this but I'm not sure so I'm not labeling this as a bug.

**Comment by Aga-C** [comment]
When creating an event list widget, there is a setting on the top `Show events happening:` where you can select how many days in advance you want to see.
