### ISSUE TITLE
Filter Events, Tasks, Reminders, Birthdays, Holidays (types), 

### ISSUE THREAD

**Issue by Rexadev** [FossifyOrg/Calendar#93]
1. **UI** - Like in `Google Calendar`, have a side panel on left with list of accounts and sub types (events, tasks...) as sub category.
2. Synced Google Calendar has option to sync **holiday types** like Christian, Muslim, UK, German... https://github.com/FossifyOrg/Calendar/issues/95
3. **separate Tasks and Reminder App** with integration with Calendar.  https://github.com/FossifyOrg/Calendar/discussions/94

https://github.com/SimpleMobileTools/Simple-Calendar/issues/1902

![image](https://github.com/FossifyOrg/Calendar/assets/62152714/d21ebd21-a666-4d04-9247-b054f2818aa7)

**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Option to filter events by - Tasks, Reminder, Holiday, Birthdays

**Describe alternatives you've considered**
Using Google Calendar

**Additional context**
None

**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Comment by Aga-C** [comment]
> Synced Google Calendar has option to sync holiday types like Christian, Muslim, UK, German...

There is already a function to import holidays for given country. If you also like to have religious holidays, you can raise a separate feature request for this.

> I would be nice to have a separate Tasks and Reminder App with integration with Simple-Calendar.

You can raise such idea in [Discussions](https://github.com/FossifyOrg/Calendar/discussions).

> UI - Like in Google Calendar, have a side panel on left with list of accounts and sub types (events, tasks...) as sub category.

Since as I understand this is your main request here, please fill the template properly describing how you see this. It will help us understand better what exactly you'd like to have done.

**Comment by Rexadev** [comment]
@Aga-C Please check now

**Comment by Aga-C** [comment]
> Where

In the calendar view at the bottom, you can tap an event type to toggle its visibility. You can also decide via settings, which event types should be visible at the bottom bar (`Manage quick filter event types`).
