### ISSUE TITLE
Option to Hide event options in bottom bar

### ISSUE THREAD

**Issue by MehrabShawon** [FossifyOrg/Calendar#96]
It'll be been great if we can hide the bottom bar which show/hides holodays/events/tasks (shown in photos).
![Screenshot_20240124-005401~2](https://github.com/FossifyOrg/Calendar/assets/116424330/f2aacee6-7c47-4efa-a848-74bd67ee2de2)

We can choose which events/tasks to show just by clicking the right side icon of three dots. 
![Screenshot_20240124-005401~3](https://github.com/FossifyOrg/Calendar/assets/116424330/f21e9b64-ec60-4e69-b067-3955597bc96c)

So the bottom bar which show or hides holidays/events/tasks isn't nessarary for everyone. Hope you'll take it into consideration and add this if possible. 

Hope you have a good day/night.. and thanks for the project!

**Comment by Aga-C** [comment]
You can hide it in Settings -> Manage quick filter event types.

**Comment by dktzde** [comment]
Hi Aga,

Thank you very much for the quick reply. I had already opened this menu item - but hadn't tested it. I thought the calendar would no longer be displayed. Perhaps it is possible to rename this entry. e.g. to "Manage quick filter event types (displayed at the bottom of the calendar view)"

best regards Dominik
